vich_uploader:
    db_driver: orm

    mappings:
        firstimages:
           uri_prefix: /images/products/first
           upload_destination: '%kernel.project_dir%/public/images/products/first'

        attachement:
           uri_prefix: /images/products/second
           upload_destination: '%kernel.project_dir%/public/images/products/second'
        
        category_image:
           uri_prefix: /images/category
           upload_destination: '%kernel.project_dir%/public/images/category'
